### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by Zeitkind** [kosma/bakingbread#2]
on OS X:
 $ make
gcc -Wall -O2 -std=gnu99 -fnested-functions  -lao  bread.c   -o bread
bread.c:26:24: error: function definition is not allowed here
    void cleanup(void) {
                       ^
bread.c:30:12: error: use of undeclared identifier 'cleanup'; did you mean 'cgetnum'?
    atexit(cleanup);
           ^~~~~~~
           cgetnum
/usr/include/stdlib.h:262:6: note: 'cgetnum' declared here
int      cgetnum(char *, const char *, long *);
         ^
2 errors generated.
make: *** [bread] Error 1
Any hints?

Edit: Nested functions won't compile on clang, it's a gcc-special addition.

**Comment by kosma** [comment]
That must've been a past-life me, thinking only about my own sorry Linux ass... fixed on master (dc7eb26). :)
